import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "../styles/main.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${inter.className}`}>
        <section className={`${styles.section} ${styles.section__hero}`}>
          <div className={`${styles.container}`}>
            <div className={`${styles.hero}`}>
              <h1>Hello Developer!</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
            </div>
          </div>
        </section>
        <section className={`${styles.section}`}>
          <div className={`${styles.container}`}>
            <div className={`${styles.cards__list}`}>
              <div className={`${styles.card}`}>
                <img
                  src="/assets/400x300.png"
                  className={`${styles.card__image}`}
                />
                <p className={styles.card__text}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Curabitur iaculis, nunc quis maximus laoreet, nibh sem iaculis
                  sapien, ac maximus felis diam vel diam. Integer finibus, sem
                  et gravida pulvinar, leo lectus malesuada est, a ornare ipsum
                  massa eget sem
                </p>
                <button className={styles.card__button}>Read More</button>
              </div>
              <div className={`${styles.card}`}>
                <img
                  src="/assets/400x300.png"
                  className={`${styles.card__image}`}
                />
                <p className={styles.card__text}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Curabitur iaculis
                </p>
                <button className={styles.card__button}>Read More</button>
              </div>
              <div className={`${styles.card}`}>
                <img
                  src="/assets/400x300.png"
                  className={`${styles.card__image}`}
                />
                <p className={styles.card__text}>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Curabitur iaculis, nunc quis maximus laoreet, nibh sem iaculis
                  sapien, ac maximus felis diam vel diam. Integer finibus, sem
                  et gravida pulvinar. Quisque venenatis, lorem quis ultrices
                  finibus
                </p>
                <button className={styles.card__button}>Read More</button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
